### PR TITLE
Rebuild for PyPy3.8 and PyPy3.9 (redux)

### PR DESCRIPTION
**Pull request by h-vetinari**
Continuing from #96

Closes #96

### CODE REVIEW

**Comment by anton-malakhov** [comment]
The refactoring looks good to me. Though why did you disable aarch64 target?

**Comment by h-vetinari** [comment]
> The refactoring looks good to me. Though why did you disable aarch64 target?

I didn't disable it - it's still being built (check re-added travis build), but not by cross-compilation. :)

**Comment by h-vetinari** [comment]
@mattip, so the osx failure I was looking at in #96:
> [...] OSX gets the farthest currently, fails the tbbpy tests by not timing out as expected [here](https://github.com/oneapi-src/oneTBB/blob/v2021.5.0/python/tbb/test.py#L138-L145)

seems to be some sort of race-condition. It passed in the first run here, but failed again in the second.

**Comment by h-vetinari** [comment]
> it's still being built, but not by cross-compilation.

... which was also the previous state of this feedstock before https://github.com/conda-forge/tbb-feedstock/pull/97/commits/0217c37a1dad1d5445bab7369fb33d64a33373e6 added it, df. https://github.com/regro/cf-scripts/issues/1518

**Comment by h-vetinari** [comment]
OK, windows builds are passing now. Not sure why ninja doesn't like these `CMAKE_GENERATOR_*` variables...

Just double-checking with @isuruf that unsetting `CMAKE_GENERATOR_TOOLSET=v141` will not change ABI here...?

OSX is flaky as mentioned above - could be solvable with restarts, but would be nicer if we can fix it comprehensively.

**Comment by mattip** [comment]
Thanks for looking into this

**Comment by mattip** [comment]
All checks pass here. Is there more to do?

**Review by anton-malakhov — APPROVED** [review]

**Comment by h-vetinari** [comment]
> All checks pass here. Is there more to do?

Well, the flaky test / race condition presumably hasn't gone, it's just that someone restarted the CI. If people are fine with occasionally having to restart failed jobs, I guess it's a minor enough failure to merge, but that's a decision for @conda-forge/tbb

**Comment by anton-malakhov** [comment]
It has been observed before this PR. I recommend merging and dealing with the failure in a separate issue. The simple approach is to disable tbb4py on OSX

**Comment by h-vetinari** [comment]
Ah, I didn't know that it was pre-existing! In this case, definitely, go ahead and merge from my POV (though I wouldn't disable `tbb4py` on osx, maaaaaaaybe just the tests, but not the package itself).

**Comment by anton-malakhov** [comment]
OK, if nobody objects, I'll merge it tomorrow. Thanks for your effort! Ping @AlexVeprev

**Comment by h-vetinari** [comment]
> Just double-checking with @isuruf that unsetting `CMAKE_GENERATOR_TOOLSET=v141` will not change ABI here...?

One last FYI-ping on this. Otherwise it sounds like we're good to go.

**Comment by isuruf** [comment]
> Just double-checking with @isuruf that unsetting CMAKE_GENERATOR_TOOLSET=v141 will not change ABI here...?

Yes, it doesn't.

**Comment by mattip** [comment]
Thanks!

**Comment by h-vetinari** [comment]
Thanks all!

@anton-malakhov, the OSX build failed upon merging to main - could you please restart it?

**Comment by anton-malakhov** [comment]
Hmm.. I have Azure account but it looks like I don't have the rights to restart. @isuruf please help

**Comment by h-vetinari** [comment]
> Hmm.. I have Azure account but it looks like I don't have the rights to restart.

For non-core members, the restart is only available from the GH UI (when you click on "Details" for any CI run, there's a "Re-run" button on the left), not within Azure itself.

But looks like it got restarted already. :)

**Comment by AlexVeprev** [comment]
Hi, there is https://github.com/oneapi-src/oneTBB/issues/377 for sporadic macOS failures

**Comment by anton-malakhov** [comment]
There's also a problem with Travis. I cannot login. Please restart

**Pull request merged**
