### PR TITLE
Fix Windows builds

### PR DESCRIPTION
**Pull request by jakirkham**
Was not properly tracking Windows VC version previously. This should fix it.

### CODE REVIEW

**Comment by jschueller** [comment]
should I apply this to https://github.com/conda-forge/muparser-feedstock ?

**Comment by jschueller** [comment]
how do you generate the "re-render with ..." commit ? is there a command I should know ?

**Comment by jschueller** [comment]
@jakirkham, I see what this does now, it generates a version for each 3 vc runtime, seems ready ?

**Comment by jakirkham** [comment]
> should I apply this to https://github.com/conda-forge/muparser-feedstock ?

Yes.

> how do you generate the "re-render with ..." commit ? is there a command I should know ?

1. Change the recipe as I did in the first commit ( https://github.com/conda-forge/tbb-feedstock/pull/1/commits/049444843a128decc84a6aab42bb9f6b0d42be50 ).
2. Install `conda-smithy` ( `conda install -c conda-forge conda-smithy` ).
3. Run `conda smithy rerender` at the top level directory of this repo.
4. Add and commit all changes.
...the rest you have done before.

>  @jakirkham, I see what this does now, it generates a version for each 3 vc runtime, seems ready ?

Exactly. It is. I should/will remove WIP now.

**Comment by jschueller** [comment]
Ok thanks!

**Pull request merged**
