### PR TITLE
Update to v2021.3.0, update patches, install to LIBRARY_PREFIX on Windows

### PR DESCRIPTION
**Pull request by AlexVeprev**
Signed-off-by: Veprev, Alexey <alexey.veprev@intel.com>

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by AlexVeprev** [comment]
Travis CI (linux_ppc64le_) fails due to https://github.com/oneapi-src/oneTBB/issues/430 that has been recently fixed in scope of https://github.com/oneapi-src/oneTBB/pull/461. I'll apply patch here.

**Comment by AlexVeprev** [comment]
@conda-forge-admin, please rerender

**Comment by AlexVeprev** [comment]
This PR fixes #86.

Now it looks as expected to me, @sdebionne, @mgouicem, you may want to take a look.

Before this PR (tbb, tbb-devel and tbb4py are installed to `%PREFIX%`):
```
...
2021-06-25T11:09:35.2567077Z -- Install component: "runtime"
2021-06-25T11:09:35.2580253Z -- Installing: D:/bld/tbb_1624618788751/_h_env/bin/tbb12.dll
2021-06-25T11:09:35.2597893Z -- Installing: D:/bld/tbb_1624618788751/_h_env/bin/tbbmalloc.dll
2021-06-25T11:09:35.2612262Z -- Installing: D:/bld/tbb_1624618788751/_h_env/bin/tbbmalloc_proxy.dll
...
2021-06-25T11:13:37.4567907Z -- Install component: "devel"
2021-06-25T11:13:37.4569348Z -- Installing: D:/bld/tbb_1624618788751/_h_env/include
2021-06-25T11:13:37.4576685Z -- Installing: D:/bld/tbb_1624618788751/_h_env/include/oneapi
2021-06-25T11:13:37.4579550Z -- Installing: D:/bld/tbb_1624618788751/_h_env/include/oneapi/tbb
2021-06-25T11:13:37.4584875Z -- Installing: D:/bld/tbb_1624618788751/_h_env/include/oneapi/tbb/blocked_range.h
...
2021-06-25T11:16:28.2029054Z -- Install component: "tbb4py"
2021-06-25T11:16:28.2055303Z -- Up-to-date: D:/bld/tbb_1624618788751/_h_env/.
2021-06-25T11:16:28.2061169Z -- Up-to-date: D:/bld/tbb_1624618788751/_h_env/./Lib
2021-06-25T11:16:28.2063159Z -- Up-to-date: D:/bld/tbb_1624618788751/_h_env/./Lib/site-packages
2021-06-25T11:16:28.2067517Z -- Installing: D:/bld/tbb_1624618788751/_h_env/./Lib/site-packages/tbb
2021-06-25T11:16:28.2070118Z -- Installing: D:/bld/tbb_1624618788751/_h_env/./Lib/site-packages/tbb/api.py
2021-06-25T11:16:28.2076283Z -- Installing: D:/bld/tbb_1624618788751/_h_env/./Lib/site-packages/tbb/pool.py
...
```

With this PR (tbb and tbb-devel are installed to `%LIBRARY_PREFIX%`, tbb4py is installed to `%PREFIX%`):
```
...
2021-06-30T12:58:30.2389387Z -- Install component: "runtime"
2021-06-30T12:58:30.2400628Z -- Installing: D:/bld/tbb_1625057119515/_h_env/Library/bin/tbb12.dll
2021-06-30T12:58:30.2442675Z -- Installing: D:/bld/tbb_1625057119515/_h_env/Library/bin/tbbmalloc.dll
2021-06-30T12:58:30.2457179Z -- Installing: D:/bld/tbb_1625057119515/_h_env/Library/bin/tbbmalloc_proxy.dll
...
2021-06-30T13:00:59.7379648Z -- Install component: "devel"
2021-06-30T13:00:59.7381588Z -- Installing: D:/bld/tbb_1625057119515/_h_env/Library/include
2021-06-30T13:00:59.7382970Z -- Installing: D:/bld/tbb_1625057119515/_h_env/Library/include/oneapi
2021-06-30T13:00:59.7384873Z -- Installing: D:/bld/tbb_1625057119515/_h_env/Library/include/oneapi/tbb
2021-06-30T13:00:59.7389553Z -- Installing: D:/bld/tbb_1625057119515/_h_env/Library/include/oneapi/tbb/blocked_range.h
...
2021-06-30T13:03:47.4935121Z -- Install component: "tbb4py"
2021-06-30T13:03:47.4968508Z -- Up-to-date: D:/bld/tbb_1625057119515/_h_env/.
2021-06-30T13:03:47.4977141Z -- Up-to-date: D:/bld/tbb_1625057119515/_h_env/./Lib
2021-06-30T13:03:47.4987613Z -- Up-to-date: D:/bld/tbb_1625057119515/_h_env/./Lib/site-packages
2021-06-30T13:03:47.5020725Z -- Installing: D:/bld/tbb_1625057119515/_h_env/./Lib/site-packages/tbb
2021-06-30T13:03:47.5027271Z -- Installing: D:/bld/tbb_1625057119515/_h_env/./Lib/site-packages/tbb/api.py
2021-06-30T13:03:47.5035415Z -- Installing: D:/bld/tbb_1625057119515/_h_env/./Lib/site-packages/tbb/pool.py
...
```

**Comment by sdebionne** [comment]
LGTM, thanks!

**Pull request merged**
