### PR TITLE
update to 2020.2

### PR DESCRIPTION
**Pull request by anton-malakhov**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by anton-malakhov** [comment]
@conda-forge-admin, please rerender

**Comment by anton-malakhov** [comment]
I have absolutely no time to fix the build :(
I'll merge it as is if nobody speaks up soon.
It will give us at least Linux build for new version
Meanwhile, I'll kindly ask @AlexVeprev to look into problems on other platforms

**Comment by anton-malakhov** [comment]
Sorry I messed up with branch not from a fork. Thus I'm merging now as some packages are already published

**Comment by beckermr** [comment]
We really should not have merged this PR, especially on a low-level library like this w/ disabled tests. To add to the trouble, it was not made from a fork and so we don't actually know which version of the recipe was uploaded. 

@conda-forge/core What do you all think about marking this version as broken and backing this PR out?

**Comment by xhochy** [comment]
> @conda-forge/core What do you all think about marking this version as broken and backing this PR out?

Sounds reasonable.

**Comment by isuruf** [comment]
IMO, we should keep it as it is, unless the maintenance team (@anton-malakhov and @jschueller) wants to revert it.

**Comment by beckermr** [comment]
What is your reasoning @isuruf? I am curious.

**Comment by anton-malakhov** [comment]
> We really should not have merged this PR, especially on a low-level library like this w/ disabled tests

Sorry once again for causing the troubles. I didn't expect CI to be so stubborn. :( Quick editing right in the github is so tempting...

TBB has well-established pre-release testing procedure, so, there is no need to test TBB functionality here too deep. Also, the reasons of the failing tests are not severe, e.g. cmake could not find _debug library and OSX just hangs on the build stage - which is also not related to the library functionality itself. My choice was to publish new version where it works (Linux) or not to publish it at all.. I hope this incident will attract attention of TBB developers so they will help here :) As well as your attention is attracted to non-fork branches. I believe, they can either be enforced or fixed for convenience of maintainers ;)

**Comment by AlexVeprev** [comment]
The problem with not found debug library should be resolved with my old PR #62, I haven't finished it because of some errors in CI.
Also I wasn't able to reproduce hangs on macOS locally.

BTW, does it make sense to proceed with the fixes in TBB 2020 or it's better to focus on newer upcoming release oneTBB 2021 once it's published and the question #75 resolved?

**Pull request merged**
